// Run only against a fresh isolated Wiki instance. No production accounts or email are used.
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import { writeFile } from 'node:fs/promises'
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
const base = process.env.TEST_WIKI_URL
if (!base || !/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base)) throw Error('TEST_WIKI_URL must be an isolated loopback URL')
const report = { startedAt: new Date().toISOString(), checks: [] }
const clients = []
const secret = () => crypto.randomBytes(24).toString('base64url')
const headers = jwt => ({ 'Content-Type': 'application/json', Cookie: `jwt=${jwt}`, 'x-ewo-mcp-ui': '1' })
async function http (path, body, jwt) {
 return fetch(base+path,{method:body===undefined?'GET':'POST',headers:jwt?headers(jwt):{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual',signal:AbortSignal.timeout(60000)})
}
async function graph(q, variables={}, jwt) { const r=await http('/graphql',{query:q,variables},jwt); const b=await r.json(); if(b.errors)throw Error(JSON.stringify(b.errors.map(x=>x.message))); return b.data }
async function login(email,password){const b=await graph('mutation($u:String!,$p:String!){authentication{login(username:$u,password:$p,strategy:"local"){responseResult{succeeded message} jwt}}}',{u:email,p:password}); assert.ok(b.authentication.login.responseResult.succeeded);return b.authentication.login.jwt}
async function token(jwt,scopes){const b=await graph('mutation($scopes:[String!]){authentication{createPersonalToken(name:"acceptance",expiresIn:"180d",scopes:$scopes){responseResult{succeeded message} token tokenInfo{id scopes}}}}',{scopes},jwt);assert.ok(b.authentication.createPersonalToken.responseResult.succeeded);return b.authentication.createPersonalToken}
async function connect(key){const c=new Client({name:'acceptance',version:'1.0.0'});await c.connect(new StreamableHTTPClientTransport(new URL(base+'/mcp'),{requestInit:{headers:{Authorization:`Bearer ${key}`}}}));clients.push(c);return c}
async function call(c,name,args){const r=await c.callTool({name,arguments:args});return {bad:!!r.isError,...JSON.parse(r.content[0].text)}}
async function check(name,fn){try{const result=await fn();report.checks.push({name,pass:true,...result});console.log('PASS',name)}catch(e){report.checks.push({name,pass:false,error:e.message});throw e}finally{if(process.env.TEST_REPORT)await writeFile(process.env.TEST_REPORT,JSON.stringify(report,null,2))}}
let admin,aliceJwt,key,c,page,publicPage
try {
 const pass=secret()
 await check('fresh setup',async()=>{const r=await http('/finalize',{siteUrl:base,adminEmail:'admin@ewo.so',adminPassword:pass,telemetry:false});assert.equal(r.status,200);assert.equal((await r.json()).ok,true)})
 for(let i=0;i<40;i++){try{const r=await http('/graphql',{query:'{__typename}'});if((await r.text()).includes('Query'))break}catch{}await new Promise(r=>setTimeout(r,500))}
 admin=await login('admin@ewo.so',pass)
 const groups=await graph('{groups{list{id name}}}',{},admin);const group=groups.groups.list.find(x=>x.name==='Team Members');assert.ok(group)
 const password=secret()
 const created=await graph('mutation($p:String!,$g:[Int]!){users{create(email:"alice@ewo.so",name:"Alice",passwordRaw:$p,providerKey:"local",groups:$g,mustChangePassword:false,sendWelcomeEmail:false){responseResult{succeeded message}}}}',{p:password,g:[group.id]},admin);assert.ok(created.users.create.responseResult.succeeded)
 aliceJwt=await login('alice@ewo.so',password)
 key=await token(aliceJwt);c=await connect(key.token)
 await check('member PAT and SDK tools/list',async()=>{const tools=await c.listTools();assert.equal(tools.tools.length,9);const identity=await call(c,'wiki_get_identity',{});assert.equal(identity.email,'alice@ewo.so');assert.ok(identity.userId!==1);return {tools:tools.tools.length,userId:identity.userId}})
 await check('token metadata excludes secrets',async()=>{const x=await graph('{authentication{personalTokens{id name tokenPrefix scopes expiresAt revokedAt}}}',{},aliceJwt);assert.ok(!JSON.stringify(x).includes(key.token))})
 const input={title:'中文并发验收',content:'# Native Post\n\nMCP body v1',visibility:'team',publish:true,tags:['验收','MCP'],project:'中文项目',idempotencyKey:secret()}
 await check('create team Post with real author',async()=>{page=await call(c,'wiki_create_post',input);assert.equal(page.bad,false);assert.equal(page.status,'published');assert.equal(page.creatorId,(await call(c,'wiki_get_identity',{})).userId);return {postId:page.postId,path:page.path}})
 await check('idempotent Unicode title and payload conflict',async()=>{assert.equal((await call(c,'wiki_create_post',input)).postId,page.postId);assert.equal((await call(c,'wiki_create_post',{...input,content:'different'})).code,'IDEMPOTENCY_CONFLICT')})
 await check('concurrent create does not duplicate Post',async()=>{const request={...input,idempotencyKey:secret()};const both=await Promise.all([call(c,'wiki_create_post',request),call(c,'wiki_create_post',request)]);assert.ok(both.some(x=>!x.bad));const retry=await call(c,'wiki_create_post',request);assert.equal(retry.bad,false);assert.ok(both.filter(x=>!x.bad).every(x=>x.postId===retry.postId))})
 await check('tag and project search',async()=>{const r=await call(c,'wiki_search_posts',{tags:['验收'],project:'中文项目'});assert.ok(r.posts.some(x=>x.postId===page.postId));assert.equal((await call(c,'wiki_search_posts',{tags:['absent']})).posts.length,0)})
 await check('partial update preserves metadata',async()=>{const r=await call(c,'wiki_update_post',{postId:page.postId,content:'Updated content',expectedRevision:page.revision});assert.equal(r.bad,false);assert.ok(r.tags.includes('验收'));page=r})
 await check('concurrent compare-and-update',async()=>{const results=await Promise.all(['A','B'].map(content=>call(c,'wiki_update_post',{postId:page.postId,content,expectedRevision:page.revision})));assert.equal(results.filter(x=>!x.bad).length,1);assert.equal(results.filter(x=>x.code==='REVISION_CONFLICT').length,1);page=results.find(x=>!x.bad)})
 await check('unknown fields and invalid input rejected',async()=>{const r=await call(c,'wiki_create_post',{...input,title:42});assert.equal(r.code,'INVALID_INPUT')})
 await check('read-only token cannot create',async()=>{const read=await token(aliceJwt,['wiki:read']);const rc=await connect(read.token);assert.equal((await call(rc,'wiki_create_post',{...input,idempotencyKey:secret()})).code,'FORBIDDEN')})
 await check('PAT cannot reach GraphQL or issue stronger tokens',async()=>{const r=await fetch(base+'/graphql',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key.token}`},body:JSON.stringify({query:'{users{profile{id}}}'})});assert.equal(r.status,403)})
 await check('admin PAT cannot bypass public confirmation',async()=>{const at=await token(admin);const ac=await connect(at.token);const r=await call(ac,'wiki_create_post',{...input,title:'Public admin',visibility:'public',idempotencyKey:secret()});assert.equal(r.status,'draft')})
 await check('public request yields draft and review link',async()=>{publicPage=await call(c,'wiki_create_post',{...input,title:'Public review',visibility:'public',idempotencyKey:secret()});assert.equal(publicPage.status,'draft');assert.ok(publicPage.reviewUrl);assert.ok((await http('/en/'+publicPage.path)).status>=400)})
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')
 let asset
 await check('private draft PNG upload and byte readback',async()=>{asset=await call(c,'wiki_upload_attachment',{postId:publicPage.postId,filename:'proof.png',mime:'image/png',dataBase64:png.toString('base64'),sha256:crypto.createHash('sha256').update(png).digest('hex')});assert.equal(asset.bad,false);const u=new URL(asset.url);assert.equal((await http(u.pathname)).status,404);const r=await http(u.pathname,undefined,aliceJwt);assert.equal(r.status,200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),png)})
 await check('public confirmation requires a browser session',async()=>{assert.equal((await http('/mcp-review/'+publicPage.postId)).status,401);const r=await fetch(base+'/mcp-review/'+publicPage.postId,{headers:{Authorization:`Bearer ${key.token}`}});assert.equal(r.status,403)})
 async function approve(){const r=await http('/mcp-review/'+publicPage.postId,undefined,aliceJwt);const markup=await r.text();assert.equal(r.status,200);const nonce=markup.match(/name="nonce" value="([a-f0-9]+)"/)[1];const cookie=(r.headers.get('set-cookie')||'').split(';')[0];const response=await fetch(base+'/mcp-review/'+publicPage.postId,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Cookie:`jwt=${aliceJwt}; ${cookie}`,Origin:base},body:new URLSearchParams({nonce,confirmed:'yes'}),redirect:'manual'});assert.equal(response.status,303)}
 await check('human confirmation publishes exact revision and attachment',async()=>{await approve();assert.equal((await http('/en/'+publicPage.path)).status,200);const r=await http(new URL(asset.url).pathname);assert.equal(r.status,200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),png)})
 await check('public edit re-enters draft even when publish omitted',async()=>{const now=await call(c,'wiki_get_post',{postId:publicPage.postId});const edited=await call(c,'wiki_update_post',{postId:now.postId,expectedRevision:now.revision,content:'New public draft'});assert.equal(edited.status,'draft');assert.ok((await http('/en/'+now.path)).status>=400);assert.equal((await http(new URL(asset.url).pathname)).status,404)})
 await check('old public confirmation cannot publish a newer revision',async()=>{const preview=await http('/mcp-review/'+publicPage.postId,undefined,aliceJwt);const markup=await preview.text();const nonce=markup.match(/name="nonce" value="([a-f0-9]+)"/)[1];const cookie=(preview.headers.get('set-cookie')||'').split(';')[0];const now=await call(c,'wiki_get_post',{postId:publicPage.postId});assert.equal((await call(c,'wiki_update_post',{postId:now.postId,expectedRevision:now.revision,content:'Changed after preview'})).bad,false);const r=await fetch(base+'/mcp-review/'+publicPage.postId,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Cookie:`jwt=${aliceJwt}; ${cookie}`,Origin:base},body:new URLSearchParams({nonce,confirmed:'yes'}),redirect:'manual'});assert.equal(r.status,400);assert.equal((await call(c,'wiki_get_post',{postId:publicPage.postId})).status,'draft')})
 await check('2 MiB attachment is streamed through the configured body limit',async()=>{const bytes=Buffer.alloc(2*1024*1024,65);const result=await call(c,'wiki_upload_attachment',{postId:page.postId,filename:'large.txt',mime:'text/plain',dataBase64:bytes.toString('base64'),sha256:crypto.createHash('sha256').update(bytes).digest('hex')});assert.equal(result.bad,false);const r=await http(new URL(result.url).pathname,undefined,aliceJwt);assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,bytes.length)})
 await check('revision history available',async()=>{const r=await call(c,'wiki_get_post_history',{postId:page.postId});assert.equal(r.bad,false);assert.ok(r.total>=2)})
 await check('native GraphQL optional tags remains functional',async()=>{const before=await call(c,'wiki_get_post',{postId:page.postId});const r=await graph('mutation($id:Int!,$r:String!){pages{update(id:$id,expectedRevision:$r,description:"Native update"){responseResult{succeeded message}}}}',{id:page.postId,r:before.revision},aliceJwt);assert.ok(r.pages.update.responseResult.succeeded)})
 await check('stdio SDK bridge works',async()=>{const local=new Client({name:'stdio-acceptance',version:'1.0.0'});await local.connect(new StdioClientTransport({command:process.execPath,args:['mcp/server.mjs'],env:{...process.env,EWO_WIKI_MCP_URL:base+'/mcp',EWO_WIKI_TOKEN:key.token},stderr:'pipe'}));clients.push(local);assert.equal((await local.listTools()).tools.length,9);assert.equal((await call(local,'wiki_get_identity',{})).email,'alice@ewo.so')})
 await check('disabled account invalidates existing Key',async()=>{const user=(await call(c,'wiki_get_identity',{})).userId;await graph('mutation($id:Int!){users{deactivate(id:$id){responseResult{succeeded}}}}',{id:user},admin);const r=await fetch(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key.token}`},body:'{}'});assert.equal(r.status,401);await graph('mutation($id:Int!){users{activate(id:$id){responseResult{succeeded}}}}',{id:user},admin)})
 await check('token revocation enforced',async()=>{await graph('mutation($id:Int!){authentication{revokePersonalToken(id:$id){responseResult{succeeded}}}}',{id:key.tokenInfo.id},aliceJwt);const r=await fetch(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key.token}`},body:'{}'});assert.equal(r.status,401)})
 console.log(JSON.stringify({passed:report.checks.length,failed:0}))
} finally {await Promise.allSettled(clients.map(c=>c.close()))}
